#!/usr/bin/env bash
# Supported production entry point. Usage: ./deploy.sh production
set -Eeuo pipefail

environment="${1:-production}"
env_file=".env.${environment}"
base_file="docker-compose.production.yml"

die() { printf 'FEHLER: %s\n' "$*" >&2; exit 1; }
info() { printf '==> %s\n' "$*"; }

[[ "$environment" == "production" ]] || die "Nur das Environment 'production' wird unterstützt."
[[ -f "$env_file" ]] || die "$env_file fehlt. Zuerst: cp .env.production.example .env.production"
command -v docker >/dev/null || die "docker ist nicht installiert."
docker compose version >/dev/null 2>&1 || die "Docker Compose v2 ist nicht verfügbar."

# The production dotenv file is maintained by the operator and uses shell-compatible
# KEY=value syntax, as generated by .env.production.example.
set -a
# shellcheck disable=SC1090
source "$env_file"
set +a

required=(
  STORAGE_PROVIDER DATABASE_URL POSTGRES_PASSWORD JWT_SECRET
  S3_ENDPOINT S3_BUCKET S3_REGION S3_ACCESS_KEY_ID S3_SECRET_ACCESS_KEY
  VITE_API_BASE_URL VITE_MAPTILER_API_KEY VITE_GM_CLIENT_URL
  ROSTER_FILE ROSTER_SHA256 EXPECTED_PLAYER_COUNT EXPECTED_TEAM_COUNT
)
for name in "${required[@]}"; do
  value="${!name-}"
  [[ -n "$value" ]] || die "$name muss in $env_file gesetzt sein."
  [[ "$value" != *CHANGE_ME* && "$value" != *'<YOUR_'* ]] || die "$name enthält noch einen Platzhalter."
done
[[ ${#JWT_SECRET} -ge 32 ]] || die "JWT_SECRET muss mindestens 32 Zeichen lang sein."
[[ -f "$ROSTER_FILE" ]] || die "ROSTER_FILE existiert nicht: $ROSTER_FILE"
[[ "$ROSTER_SHA256" =~ ^[[:xdigit:]]{64}$ ]] || die "ROSTER_SHA256 muss eine 64-stellige SHA-256-Prüfsumme sein."

compose=(docker compose --env-file "$env_file" -f "$base_file")
case "$STORAGE_PROVIDER" in
  aws)
    [[ "$S3_ENDPOINT" != http://minio:9000 ]] || die "STORAGE_PROVIDER=aws darf nicht den internen MinIO-Endpunkt verwenden."
    [[ -z "${MINIO_ROOT_USER-}" && -z "${MINIO_ROOT_PASSWORD-}" ]] || die "Bei STORAGE_PROVIDER=aws dürfen MINIO_ROOT_USER/PASSWORD nicht gesetzt sein."
    info "Storage-Variante: AWS S3 (ohne MinIO-Services)"
    ;;
  minio)
    for name in MINIO_ROOT_USER MINIO_ROOT_PASSWORD; do
      value="${!name-}"
      [[ -n "$value" ]] || die "$name muss für STORAGE_PROVIDER=minio gesetzt sein."
      [[ "$value" != *CHANGE_ME* ]] || die "$name enthält noch einen Platzhalter."
    done
    [[ ${#MINIO_ROOT_PASSWORD} -ge 8 ]] || die "MINIO_ROOT_PASSWORD muss mindestens 8 Zeichen lang sein."
    [[ "$S3_ENDPOINT" == http://minio:9000 ]] || die "Für MinIO muss S3_ENDPOINT=http://minio:9000 sein."
    [[ "$S3_ACCESS_KEY_ID" == "$MINIO_ROOT_USER" ]] || die "S3_ACCESS_KEY_ID muss für MinIO MINIO_ROOT_USER entsprechen."
    [[ "$S3_SECRET_ACCESS_KEY" == "$MINIO_ROOT_PASSWORD" ]] || die "S3_SECRET_ACCESS_KEY muss für MinIO MINIO_ROOT_PASSWORD entsprechen."
    compose+=(-f docker-compose.production.minio.yml)
    info "Storage-Variante: MinIO"
    ;;
  local)
    info "Storage-Variante: Lokal (kein MinIO / S3)"
    ;;
  *) die "STORAGE_PROVIDER muss 'aws', 'minio' oder 'local' sein (aktuell: ${STORAGE_PROVIDER})." ;;
esac

# Resolve and validate the complete selected Compose model before building or
# starting any container. Compose's ${VAR:?message} checks provide a second guard.
info "Validiere Produktionskonfiguration ..."
"${compose[@]}" config --quiet

info "Baue Images ..."
"${compose[@]}" build

# Completed one-shot containers would otherwise be reused when neither their
# image nor their configuration changed. Force their recreation so every
# deployment actually verifies the current database and approved roster.
info "Führe Release-Kette erneut aus (Migrationen, Seed, Roster, Preflight) ..."
"${compose[@]}" up -d --force-recreate migrate seed-content roster-import release-preflight

info "Starte Produktionsdienste nach erfolgreichem Preflight ..."
"${compose[@]}" up -d
info "Status der Release-Kette:"
"${compose[@]}" ps -a migrate seed-content roster-import release-preflight
