#!/usr/bin/env bash
# Supported production entry point. Usage: ./deploy.sh production
set -Eeuo pipefail

environment="${1:-production}"
env_file=".env.${environment}"
base_file="docker-compose.production.yml"

die() { printf 'FEHLER: %s\n' "$*" >&2; exit 1; }
info() { printf '==> %s\n' "$*"; }

[[ "$environment" == "production" ]] || die "Nur das Environment 'production' wird unterstützt."
[[ -f "$env_file" ]] || die "$env_file fehlt. Zuerst: cp .env.production.example .env.production"
command -v docker >/dev/null || die "docker ist nicht installiert."
docker compose version >/dev/null 2>&1 || die "Docker Compose v2 ist nicht verfügbar."

# The production dotenv file is maintained by the operator and uses shell-compatible
# KEY=value syntax, as generated by .env.production.example.
set -a
# shellcheck disable=SC1090
source "$env_file"
set +a

<<<<<<< HEAD
log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_command() {
    if ! command -v $1 &> /dev/null; then
        log_error "$1 is not installed. Please install it first."
        exit 1
    fi
}

# ─── Pre-flight Checks ───────────────────────────────────────────────────────
log_info "Starting deployment for environment: ${ENVIRONMENT}"

# Check required commands
check_command docker
check_command git

# Check if env file exists
if [ ! -f "$ENV_FILE" ]; then
    log_error "Environment file $ENV_FILE not found!"
    log_info "Please create it from .env.example"
    exit 1
fi

# Load environment variables
log_info "Loading environment from $ENV_FILE"
export $(cat $ENV_FILE | grep -v '^#' | xargs)

# ─── Git Operations ──────────────────────────────────────────────────────────
log_info "Pulling latest code from git..."
git fetch origin
CURRENT_COMMIT=$(git rev-parse HEAD)
log_info "Current commit: ${CURRENT_COMMIT:0:8}"

# Optional: Check if we're on the right branch
BRANCH=$(git rev-parse --abbrev-ref HEAD)
log_info "Current branch: $BRANCH"

# ─── Backup Database ─────────────────────────────────────────────────────────
log_info "Creating database backup..."
BACKUP_DIR="./backups"
mkdir -p $BACKUP_DIR
BACKUP_FILE="${BACKUP_DIR}/backup_$(date +%Y%m%d_%H%M%S).sql"

if docker compose -f $DOCKER_COMPOSE_FILE --env-file $ENV_FILE ps postgres | grep -q "Up"; then
    docker compose -f $DOCKER_COMPOSE_FILE --env-file $ENV_FILE exec -T postgres \
        pg_dump -U ${POSTGRES_USER:-postgres} ${POSTGRES_DB:-jugendleiter2026} > "$BACKUP_FILE" 2>/dev/null || true
    
    if [ -f "$BACKUP_FILE" ]; then
        log_info "Backup created: $BACKUP_FILE"
        
        # Keep only last 7 backups
        ls -t $BACKUP_DIR/backup_*.sql | tail -n +8 | xargs -r rm
    else
        log_warn "Backup failed, but continuing deployment..."
    fi
else
    log_warn "PostgreSQL container not running, skipping backup"
fi

# ─── Build Docker Images ─────────────────────────────────────────────────────
log_info "Building Docker images..."
docker compose -f $DOCKER_COMPOSE_FILE --env-file $ENV_FILE build --no-cache

# ─── Stop Old Containers ─────────────────────────────────────────────────────
log_info "Stopping old containers..."
docker compose -f $DOCKER_COMPOSE_FILE --env-file $ENV_FILE down

# ─── Start New Containers ────────────────────────────────────────────────────
log_info "Starting new containers..."
docker compose -f $DOCKER_COMPOSE_FILE --env-file $ENV_FILE up -d

# ─── Wait for Services ───────────────────────────────────────────────────────
log_info "Waiting for services to be healthy..."
sleep 10

# Check PostgreSQL
log_info "Checking PostgreSQL..."
until docker compose -f $DOCKER_COMPOSE_FILE --env-file $ENV_FILE exec -T postgres pg_isready -U ${POSTGRES_USER:-postgres} > /dev/null 2>&1; do
    log_warn "PostgreSQL is unavailable - sleeping"
    sleep 2
=======
required=(
  STORAGE_PROVIDER DATABASE_URL POSTGRES_PASSWORD JWT_SECRET
  S3_ENDPOINT S3_BUCKET S3_REGION S3_ACCESS_KEY_ID S3_SECRET_ACCESS_KEY
  VITE_API_BASE_URL VITE_MAPTILER_API_KEY VITE_GM_CLIENT_URL
  ROSTER_FILE ROSTER_SHA256 EXPECTED_PLAYER_COUNT EXPECTED_TEAM_COUNT
)
for name in "${required[@]}"; do
  value="${!name-}"
  [[ -n "$value" ]] || die "$name muss in $env_file gesetzt sein."
  [[ "$value" != *CHANGE_ME* && "$value" != *'<YOUR_'* ]] || die "$name enthält noch einen Platzhalter."
>>>>>>> 1e834fe223cf8e6a8eedd118fa4fce48e4df7c33
done
[[ ${#JWT_SECRET} -ge 32 ]] || die "JWT_SECRET muss mindestens 32 Zeichen lang sein."
[[ -f "$ROSTER_FILE" ]] || die "ROSTER_FILE existiert nicht: $ROSTER_FILE"
[[ "$ROSTER_SHA256" =~ ^[[:xdigit:]]{64}$ ]] || die "ROSTER_SHA256 muss eine 64-stellige SHA-256-Prüfsumme sein."

compose=(docker compose --env-file "$env_file" -f "$base_file")
case "$STORAGE_PROVIDER" in
  aws)
    [[ "$S3_ENDPOINT" != http://minio:9000 ]] || die "STORAGE_PROVIDER=aws darf nicht den internen MinIO-Endpunkt verwenden."
    [[ -z "${MINIO_ROOT_USER-}" && -z "${MINIO_ROOT_PASSWORD-}" ]] || die "Bei STORAGE_PROVIDER=aws dürfen MINIO_ROOT_USER/PASSWORD nicht gesetzt sein."
    info "Storage-Variante: AWS S3 (ohne MinIO-Services)"
    ;;
  minio)
    for name in MINIO_ROOT_USER MINIO_ROOT_PASSWORD; do
      value="${!name-}"
      [[ -n "$value" ]] || die "$name muss für STORAGE_PROVIDER=minio gesetzt sein."
      [[ "$value" != *CHANGE_ME* ]] || die "$name enthält noch einen Platzhalter."
    done
    [[ ${#MINIO_ROOT_PASSWORD} -ge 8 ]] || die "MINIO_ROOT_PASSWORD muss mindestens 8 Zeichen lang sein."
    [[ "$S3_ENDPOINT" == http://minio:9000 ]] || die "Für MinIO muss S3_ENDPOINT=http://minio:9000 sein."
    [[ "$S3_ACCESS_KEY_ID" == "$MINIO_ROOT_USER" ]] || die "S3_ACCESS_KEY_ID muss für MinIO MINIO_ROOT_USER entsprechen."
    [[ "$S3_SECRET_ACCESS_KEY" == "$MINIO_ROOT_PASSWORD" ]] || die "S3_SECRET_ACCESS_KEY muss für MinIO MINIO_ROOT_PASSWORD entsprechen."
    compose+=(-f docker-compose.production.minio.yml)
    info "Storage-Variante: MinIO"
    ;;
  *) die "STORAGE_PROVIDER muss genau 'aws' oder 'minio' sein (aktuell: ${STORAGE_PROVIDER})." ;;
esac

<<<<<<< HEAD
if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
    log_error "Backend failed to start!"
    docker compose -f $DOCKER_COMPOSE_FILE --env-file $ENV_FILE logs backend
    exit 1
fi
log_info "Backend is up!"

# Fail closed if content, teams or participant accounts are incomplete.
log_info "Running release preflight (content + event roster)..."
docker compose -f $DOCKER_COMPOSE_FILE --env-file $ENV_FILE run --rm \
    -e EXPECTED_PLAYER_COUNT="${EXPECTED_PLAYER_COUNT:-0}" \
    -e EXPECTED_TEAM_COUNT="${EXPECTED_TEAM_COUNT:-0}" \
    backend pnpm run release:preflight
=======
# Resolve and validate the complete selected Compose model before building or
# starting any container. Compose's ${VAR:?message} checks provide a second guard.
info "Validiere Produktionskonfiguration ..."
"${compose[@]}" config --quiet

info "Baue Images ..."
"${compose[@]}" build
>>>>>>> 1e834fe223cf8e6a8eedd118fa4fce48e4df7c33

# Completed one-shot containers would otherwise be reused when neither their
# image nor their configuration changed. Force their recreation so every
# deployment actually verifies the current database and approved roster.
info "Führe Release-Kette erneut aus ..."
"${compose[@]}" up -d --force-recreate migrate seed-content roster-import release-preflight

<<<<<<< HEAD
# Backend health
BACKEND_HEALTH=$(curl -s http://localhost:3000/health || echo "fail")
if [[ "$BACKEND_HEALTH" == *'"status":"ok"'* ]]; then
    log_info "✓ Backend health check passed"
else
    log_error "✗ Backend health check failed"
    docker compose -f $DOCKER_COMPOSE_FILE --env-file $ENV_FILE logs --tail=50 backend
    exit 1
fi

# Frontend health
FRONTEND_HEALTH=$(curl -s http://localhost:5173/health || echo "fail")
if [[ "$FRONTEND_HEALTH" == *"healthy"* ]]; then
    log_info "✓ Frontend health check passed"
else
    log_warn "✗ Frontend health check failed (might be OK if using Nginx)"
fi

# GM Client health
GM_HEALTH=$(curl -s http://localhost:5174/health || echo "fail")
if [[ "$GM_HEALTH" == *"healthy"* ]]; then
    log_info "✓ GM Client health check passed"
else
    log_warn "✗ GM Client health check failed (might be OK if using Nginx)"
fi

# ─── Cleanup ─────────────────────────────────────────────────────────────────
log_info "Cleaning up old Docker images..."
docker image prune -f

# ─── Summary ─────────────────────────────────────────────────────────────────
log_info "═══════════════════════════════════════════════════════════════════"
log_info "Deployment completed successfully! 🚀"
log_info "═══════════════════════════════════════════════════════════════════"
log_info "Environment: ${ENVIRONMENT}"
log_info "Commit: ${CURRENT_COMMIT:0:8}"
log_info "Timestamp: $(date)"
log_info ""
log_info "Services:"
log_info "  - Backend:    http://localhost:3000"
log_info "  - Frontend:   http://localhost:5173"
log_info "  - GM Client:  http://localhost:5174"
log_info ""
log_info "Next steps:"
log_info "  1. Check logs: docker compose -f $DOCKER_COMPOSE_FILE --env-file $ENV_FILE logs -f"
log_info "  2. Check status: docker compose -f $DOCKER_COMPOSE_FILE --env-file $ENV_FILE ps"
log_info "  3. Test endpoints: curl http://localhost:3000/health"
log_info "═══════════════════════════════════════════════════════════════════"
=======
info "Starte Produktionsdienste nach erfolgreichem Preflight ..."
"${compose[@]}" up -d
info "Status der Release-Kette:"
"${compose[@]}" ps -a migrate seed-content roster-import release-preflight
>>>>>>> 1e834fe223cf8e6a8eedd118fa4fce48e4df7c33
