import { useState, type FormEvent } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import type { CreatedPlayerAccount, GMTeamOption } from "@jlw/contracts";
import { gmFetch } from "../lib/api";
export function AccountPanel() {
  const { data: teams = [] } = useQuery({ queryKey: ["gm", "account-teams"], queryFn: () => gmFetch<GMTeamOption[]>("/gm/accounts/teams") });
  const [username,setUsername]=useState(""); const [playerName,setPlayerName]=useState(""); const [accessCode,setAccessCode]=useState(""); const [teamId,setTeamId]=useState(""); const [newTeamName,setNewTeamName]=useState("");
  const create=useMutation({ mutationFn:()=>gmFetch<CreatedPlayerAccount>("/gm/accounts/players",{method:"POST",body:JSON.stringify({username,playerName:playerName||undefined,accessCode,...(newTeamName?{newTeamName}:{teamId})})}) });
  const submit=(e:FormEvent)=>{e.preventDefault();create.mutate();};
  return <form onSubmit={submit} className="mx-auto max-w-xl space-y-4 p-6"><h2 className="text-2xl font-bold">Spieleraccount erstellen</h2><p className="text-sm text-slate-400">Die Klasse wird bewusst vom Spieler gewählt und gemäss GDD erst bei Bestätigung dauerhaft gebunden.</p>{[["Benutzername",username,setUsername],["Anzeigename",playerName,setPlayerName],["Zugangscode",accessCode,setAccessCode]].map(([label,value,setter])=><label key={label as string} className="block text-sm">{label as string}<input value={value as string} onChange={e=>(setter as (v:string)=>void)(e.target.value)} type={label==="Zugangscode"?"password":"text"} className="mt-1 w-full rounded bg-slate-800 p-3" required={label!=="Anzeigename"}/></label>)}<label className="block text-sm">Bestehendes Team<select value={teamId} onChange={e=>{setTeamId(e.target.value);setNewTeamName("");}} className="mt-1 w-full rounded bg-slate-800 p-3"><option value="">Team wählen…</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="block text-sm">oder neues Team<input value={newTeamName} onChange={e=>{setNewTeamName(e.target.value);setTeamId("");}} className="mt-1 w-full rounded bg-slate-800 p-3"/></label>{create.error&&<p className="text-red-400">{create.error.message}</p>}{create.data&&<p className="text-green-400">{create.data.player.playerName} wurde im Team {create.data.team.name} erstellt.</p>}<button disabled={create.isPending||(!teamId&&!newTeamName)} className="rounded bg-blue-600 px-5 py-3 font-bold disabled:opacity-50">Account erstellen</button></form>;
}
